### ISSUE TITLE
SuperDirt protocol support

### ISSUE THREAD

**Issue by jarmitage** [Bubobubobubobubo/sardine#106]
Sardine messages to SuperDirt look like this:
```
OSC Message Received:
    time: 53.718025123933
    address: a NetAddr(127.0.0.1, 62275)
    recvPort: 57120
    msg: [ /play2, sound, bd, orbit, 0, legato, 1, gain, 1, trig, 1 ]
```

The `/play2` path is for backwards compatibility only:
https://github.com/musikinformatik/SuperDirt/blob/develop/classes/SuperDirt.sc#L333-L338

Tidal messages to SuperDirt look like this:
```
OSC Message Received:
    time: 10.919082131004
    address: a NetAddr(127.0.0.1, 6010)
    recvPort: 57120
    msg: [ /dirt/play, _id_, 1, cps, 0.5625, cycle, 2430.0, delta, 1.777777671814, orbit, 1, s, bd ]
```

`cps`, `cycle` and `delta` are the parameters that allow SuperDirt to schedule messages on time. I am not exactly sure how Tidal calculates them (maybe @yaxu can advise) but:
- You can see where these are added to Tidal messages:
https://github.com/tidalcycles/Tidal/blob/c135f6339a5b60cf649e816e5b4c30d89ab8b08a/src/Sound/Tidal/Stream.hs#L364-L367
- And you can see how SuperDirt uses them: https://github.com/musikinformatik/SuperDirt/blob/ab76e795826b3e91e13c519eae3f97dacc6397f8/classes/DirtEvent.sc#L74 https://github.com/musikinformatik/SuperDirt/blob/ab76e795826b3e91e13c519eae3f97dacc6397f8/classes/DirtEvent.sc#L102-L110

Sardine has `SuperDirtSender.py`, but for some reason the `/play2` message is being sent in:  https://github.com/Bubobubobubobubo/sardine/blob/main/sardine/io/Osc.py#L185. Probably some refactoring is needed here as well to fully address this.

**Comment by jarmitage** [comment]
You can also see how Vortex implements this here: https://github.com/tidalcycles/vortex/blob/e10e240078c37ebe74cdb66d8d08470db557a1a8/vortex/stream.py#L166

**Comment by Bubobubobubobubo** [comment]
There is this as well:
https://github.com/musikinformatik/SuperDirt/issues/29

**Comment by Bubobubobubobubo** [comment]
25d83fd is replacing `/play_2` with `/dirt/play` but it breaks `legato` by feeding a wrong `delta` value I guess.

**Comment by yaxu** [comment]
I think delta should be duration of event in cycles

**Comment by Bubobubobubobubo** [comment]
> I think delta should be duration of event in cycles

Alright, thanks! It doesn't translate really well to how events are represented around here but I will figure it out 😄
