### ISSUE TITLE
enable hush() in Quickstep to be Player specific

### ISSUE THREAD

**Issue by HighHarmonics2** [Bubobubobubobubo/sardine#112]
The hush() function used with Quickstep will shut down all players. A more refined implementation would allow the hush() function to take an argument of the specific player and shut down that player only. 

desired behavior:

- hush(Pa)  #shuts down only Pa, leaves other players running
- hush(Pa, Pb, PZ) 
- hush() #shuts down all players

Also, hush() works, but I see this error:
__init__.py", line 407, in hush
    c.remove(runner)
  File "~/sardine/sardine/clock/Clock.py", line 643, in remove
    runner = self.runners.get(func.__name__)
AttributeError: 'str' object has no attribute '__name__'

**Comment by Bubobubobubobubo** [comment]
Yes, it wasn't rewritten properly. I'll get this fixed today I guess. Thanks for mentioning it.

**Comment by HighHarmonics2** [comment]
Thanks. No rush. When I put this in I wasn't aware of Pa >> None. 
But it still should be fixed so that hush() works the same for swimming and surfing.
