### ISSUE TITLE
pip editable flag and project path should be the last argument

### ISSUE THREAD

**Issue by giohappy** [Bubobubobubobubo/sardine#150]
[This](https://github.com/Bubobubobubobubo/sardine/blob/main/docs/technical/installation.md?plain=1#L61) should be:

`pip install --find-links https://thegamecracks.github.io/python-rtmidi-wheels/ -e .`

pip complains otherwise (at least on Windows)

**Comment by thegamecracks** [comment]
Thank you for raising this issue. I had accidentally written the --editable "flag" in the wrong place when I first introduced it in 00f2a4b. Turns out it wasn't a regular flag but it expected the project directory as an argument following it.
