### ISSUE TITLE
I only have one tab in fishery web and it's partially written

### ISSUE THREAD

**Issue by Rhoumi** [Bubobubobubobubo/sardine#166]
i only have one tab in fishery web, the [0] tab and it's only written : "@swim def drum", not even a little bubo joke/reference.
:( 

there's the [*] tab actually, but this tab doesn't count !

**Comment by Bubobubobubobubo** [comment]
Adding to #162

**Comment by Bubobubobubobubo** [comment]
Fixed (I hope!)
