### ISSUE TITLE
Can't execute code in fishery web

### ISSUE THREAD

**Issue by Rhoumi** [Bubobubobubobubo/sardine#168]
It's seems that fishery web doesn't want to work with me, 
shift+enter delete the selected code.
ctrl+e add a new line and doesn't do anything.
And i can't see any logs, even with every verbose modes on possible.
maybe it's something to do with my **browser** but doesn't work either on _chromium_ or _firefox_, 
maybe it's something to do with my **keymap** but i couldn't find anything on shift+entr or ctrl+e, i'm using _Linux Mint 20.3 Una_
please help me....

**Comment by Rhoumi** [comment]
I will go back on nvim... this is how it will end.....

**Comment by Bubobubobubobubo** [comment]
Ahahahah Rémi

**Comment by Rhoumi** [comment]
It was some miss-installed things, my bad, 
re-installed everything, now sardine core not working but fishery web works, so it's an other issue
