### ISSUE TITLE
[Pycon] use of the logging library & clean/simplify some prompt message

### ISSUE THREAD

**Issue by johnchem** [Bubobubobubobubo/sardine#173]
**Situation**: the messages actually displayed in the prompt are sent by a surcharged print function. This function has the task to print at the same time into the console (using print function from the lib rich) and into a log file. Some prompt message have a special style which is more distracting that useful. This information should be printed in a simpler way.

**Proposed action**: 
-> using the `logging` lib to handle the logging in file and passing the information to the user
-> using the `rich` handler to keep the console display style while passing log information directly to the user
-> expect for the splash screen, keep the information printed into the console at bare minimum to keep an easy-to-read console style.
-> gather all the messages printed in the console into the sardine.utils.Messages to facilitate the modification / correction of the printed message

**Notes** : this issue covert the 2 actions identifies into the #162 : 
- Remove the boxes around AsyncRunner information. Something more lightweight as replacement.
- Switch current printing to logging. Precision can be added in the logging information.

**Comment by Bubobubobubobubo** [comment]
Hi! Do you intend to create a branch to address this project? This would be very welcome for the next release! :)

**Comment by Bubobubobubobubo** [comment]
@johnchem: Any update on this matter? I am be able to do it this week if not.

**Comment by johnchem** [comment]
@Bubobubobubobubo : i would not be able to work on it this week, Next week should be less crowded for me. 
if this modification can wait until end of this month, i should be able to push my code. 
Or else, i can send a PR this afternoon with my ongoing work.
In this case, could you tell me on which branch i should PR or create a branch for this issue. 
thanks
