### ISSUE TITLE
divisor fails on certain values

### ISSUE THREAD

**Issue by HighHarmonics2** [Bubobubobubobubo/sardine#189]
Divisor will accept non-integer values 0.25, 0.5, 0.75, 1.25, 1.5 etc
With values like 0.2, 0.6, 1.1, etc. no sound plays and no error

```
Pa >> d('east:2', period=1, divisor=0.5)  # works
Pa >> d('east:2', period=1, divisor=0.6) # no sound, no error

I would expect to have any divisor values.

**Comment by Bubobubobubobubo** [comment]
On a more general level, I think that there is some unused potential of fun with `div` and `rate`. I'll try to play around with this and make it better. The error you are noticing is normal and related to a modulo operation never returning `0`.
