### ISSUE TITLE
add conditional - sometimes(), often()

### ISSUE THREAD

**Issue by HighHarmonics2** [Bubobubobubobubo/sardine#190]
These were available in the Alpha version. 
It would be useful to have them or something similar. 

```
if sometimes():
    D('', i=i )
else:
    D('', i=i)
```

**Comment by Bubobubobubobubo** [comment]
They exist already: `D('', i=i, chance='sometimes')`. I can add them again on the Python side if needed.

**Comment by Bubobubobubobubo** [comment]
It it also kind of redundant with waht you can write already with the pattern language.

**Comment by Bubobubobubobubo** [comment]
Closing:
1) easy to add as a one-liner function
2) already present in the high-order functions.
