### ISSUE TITLE
period vs p need consistency in Swim and Player

### ISSUE THREAD

**Issue by HighHarmonics2** [Bubobubobubobubo/sardine#191]
period=2 or p=2 work in Player
in swim, period defaults to one and doesn't change regardless of value entered.

Ideally, period/p would be consistent between Player and \@swim.
If "period" can't be implemented in \@swim, it would be better to have an error message on use of the word.

**Comment by Bubobubobubobubo** [comment]
Hi, yes, this is a rather odd thing that has to do with the fact that we are defining aliases for various keywords for some Sardine usecase scenarios. This alias system has not been implemented everywhere but I suppose that it could work by defining that alias. I'll take a look into it.
