### ISSUE TITLE
Amphibian Variable for period value in swim doesn't accept pattern

### ISSUE THREAD

**Issue by HighHarmonics2** [Bubobubobubobubo/sardine#213]
Using the explicit Pattern Object to set the Period value in the "again" iteration code works only for single value assignment. When the Amph Var is set to a pattern, the swim function fails with an error:

BadPeriodError: Period must be a float or integer, not '0.2 0.4 0.6'

When using Amp Var anywhere outside of the again() statement, Amph Var assignment works with a pattern.

To reproduce:
- set V.p to a single value 
- set V.s first to a single value, then change it to a pattern. (See pattern assignment to Amp Var outside of again().) 
- then set V.p to a pattern - it should fail the @swim.

```python
@swim
def slicer1(p=1, i=0):
    D('kick', 
    speed=P('(v s)', i),  # the explicit Object syntax works
    #speed=V.s,  # this shorthand syntax also works
    d=1, rate=1, i=i) 
    again(slicer1, p=P('(v p)', i), i=i+1)

V.s = 1.5
V.s = '1 1.2 0.8' 

V.p = 0.5
V.p = '0.2 0.4 0.6'
```
The only way I can find to use an Amph Var pattern on period is to manually add pattern values outside of the Amph Var.

```python
@swim
def slicer1(p=1, i=0):
    D('kick', 
    speed=V.s, 
    d=1, rate=1, i=i) 
    again(slicer1, p=P('(v p) 0.2!3 0.5', i), i=i+1)

V.p = 0.5
V.s = '1 1.1 1.2'

```

**Comment by Bubobubobubobubo** [comment]
Amphibian variables are now considered deprecated.
