### ISSUE TITLE
Upload Package to PyPi

### ISSUE THREAD

**Issue by Pipazoul** [Bubobubobubobubo/sardine#23]
It would be nice to be able to install Sardine through the Pypi registry.

**Comment by Bubobubobubobubo** [comment]
Probably won't happen before #41 and fixing a few other bugs. I need more feedback before pushing this further.

**Comment by Bubobubobubobubo** [comment]
The project is now using `poetry`. It should really way more easy to prepare binary distributions for Pypi. Only #57 really missing before I can try something :)

[cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) could be integrated to this repo to generate binary distributions on major releases. It is not currently working very well with Windows builds ☠️

**Comment by Bubobubobubobubo** [comment]
This will not be done until the packaging issue is solved. Closing for now but this will be handled as soon as possible.
