### ISSUE TITLE
Setup a ci pipeline for mkdocs build to github pages

### ISSUE THREAD

**Issue by Pipazoul** [Bubobubobubobubo/sardine#24]
Add a github action to build documentation trough mkdocs

**Ressources**
https://github.com/marketplace/actions/deploy-mkdocs

**Comment by Bubobubobubobubo** [comment]
I kinda like the windmill theme: https://github.com/gristlabs/mkdocs-windmill.
It would just need a surface reskin with a different color scheme and a better logo.

**Comment by Bubobubobubobubo** [comment]
Website prototype is now online. Should be working soon.

**Comment by Bubobubobubobubo** [comment]
@Pipazoul : tried a few things such as deleting `requirements.txt` that was already provided by the mkdocs-material action or renaming the repository to lowercase (even though the error is Docker related). I don't see what else I could do but remove the Github action for now! What do you think?

**Comment by Bubobubobubobubo** [comment]
I opened an issue on the github-actions repo: [Issues #190](https://github.com/mhausenblas/mkdocs-deploy-gh-pages/issues/190).

**Comment by Bubobubobubobubo** [comment]
OK, it was a typo.. `CUSTOM_DOMAIN` was `CUSTOM DOMAIN`..
