### ISSUE TITLE
The dependency of 'LinkPython' is breaking while 'Poetry install'

### ISSUE THREAD

**Issue by arnaldorusso** [Bubobubobubobubo/sardine#61]
Hi Folks, 
First of all, thanks for sharing the passion and the results of yours codes with Sardine.
I'm getting some errors while poetry installing Sardine:
the full output is [here](https://pastebin.com/PeTfsfPr).
I have tried to pip install it, and it also returns the same error.
Do you have an old fork of this library?

Cheers!

**Comment by Bubobubobubobubo** [comment]
Hi @arnaldorusso and great to see that you are interested by Sardine :) !

As you might have seen in the issues tracker already, packaging Sardine is still a work in progress and it can be a pain to install on some systems. Depending on your OS, you will need a few additional tools to install it. You are missing CMake and GCC to build `Link-Python`, `python-rtmidi` and `rtmidi`. All the things you need are documented on the website in the installation section. 

Good luck with the installation process! Feel free to log your progress here, I'll be helping you if you need!

**Comment by arnaldorusso** [comment]
Thank you so much for your response!

I think my problem was not caused by cmake or gcc. They were installed perfectly.
I don't know how, I have finished my install, and it seems that the order of installs in Sardine may be not so clear, and I had an error reported inside `mido` lib. [following this respons](https://github.com/mido/mido/issues/145#issuecomment-363223882) I have had success!

I have another issues, and I don't know if it's better open a new one.

Cheers

**Comment by Bubobubobubobubo** [comment]
Probably worth opening another issue if this is not related to the main issue being described here. Happy to hear that you were able to install Sardine! I'll let you open a new one :)
