### ISSUE TITLE
Sardine roadmap

### ISSUE THREAD

**Issue by arnaldorusso** [Bubobubobubobubo/sardine#76]
@Bubobubobubobubo could you outline some issues for the roadmap?
I’d like to contribute, but it’s still obscured to me where to help, or test, etc…

cheers

**Comment by Bubobubobubobubo** [comment]
Hi @arnaldorusso! That's a good idea. There is no set plan of features but there are areas where improvements would be welcome before the first stable release. I propose that we use this issue to list some of them and pick up the official Github roadmap feature later on. On the top of my head:

**Easy** 

- better MIDI note handling to prevent conflicts with repeated notes (will tackle this later on this week)
- Documentation, documentation, documentation. There is never enough documentation. This can take multiple forms:
    * adding to the website by forking, writing in .md files and doing a PR.
    * recording footage of Sardine being used to do X or Y, learning by watching videos.

**Intermediate** 

- Fixing Link clock behavior. When using the MIDI Clock with `c.ppqn = 48`, the `c.phase` value will ramp up repeatedly from `0` to `48`. However, when using the Link Clock, this value will only ramp up from `1` to `46`. This is causing trouble with the **Fast Sardine** way of patterning and must be fixed as soon as possible.
- Introducing polyphony in patterns. A Sardine user called 'mugul' is already working on this and might propose a first implementation this week.

**Hard/Advanced** 

- Better packaging: this really pains me. `link-python` and `python-rtmidi` are lagging behind by not proposing wheels for Python 3.10 and Python 3.11. This must be dealt directly by proposing contributions to these packages but it can't be done easily as it needs cooperation from the maintainers on Pypi.
- Cleaning, documenting source, rewriting obscure or hard to grasp bits, improving coding style.
- Optimisation. Sardine could run faster, could be more stable, could behave better when under stress. This is a hard task that is a blend of profiling, engineering and low-level optimisations. 

I will update this list if something comes to my mind.

**Comment by Bubobubobubobubo** [comment]
I will now remove tasks that have been completed and move to a task-based representation of things to come.

**Comment by Bubobubobubobubo** [comment]
Closing to start fresh!
