### ISSUE TITLE
Better syntax for ramps

### ISSUE THREAD

**Issue by Bubobubobubobubo** [Bubobubobubobubo/sardine#87]
Ramps are written `{1,2}` or `{1,2,0.1}` for custom step specification. It works pretty well but a better and simpler syntax could be added that requires less typing. @mugulmd was proposing `[1..2]` and `[1..2,0.1]`. It currently breaks the parser but I guess it should/could work.

**Comment by mugulmd** [comment]
I can give it a try, is that okay ?

**Comment by Bubobubobubobubo** [comment]
Sure!

**Comment by Bubobubobubobubo** [comment]
Done!
