### ISSUE TITLE
Parser test is interfering with import of the library in a regular interpreter

### ISSUE THREAD

**Issue by Bubobubobubobubo** [Bubobubobubobubo/sardine#95]
**Expected behavior**: running `python3 -m asyncio` followed by `from sardine import *` must import Sardine and show the boot screen. **Problem**: in the current version, it does not import **Sardine** at all. The fix is surely to trigger the initialisation code based on context. I'll see what I can do about it.

**Comment by Bubobubobubobubo** [comment]
Fixed by dd6bb7c?

**Comment by mugulmd** [comment]
Tell me if I'm wrong, but another solution to make this work (simpler/cleaner in my opinion) would be to just create the environment variable before running `python3 -m asyncio` with `export SARDINE_INIT_SESSION=YES`, right ?

**Comment by Bubobubobubobubo** [comment]
No worries, there is a fix for it now 👍
